services:
  capture:
    build:
      context: .
      dockerfile: capture_dockerfile
    networks:
      - p2p_network
    volumes:
      - ./traffic_capture:/traffic_capture

  ultrapeer_1:
    build:
      context: .
      dockerfile: node_dockerfile
    stdin_open: true
    tty: true
    networks:
      - p2p_network
    volumes:
      - ./logs:/app/logs
    command: >
      bash -c "python secure_file_sender.py --mode ultrapeer"

  leaf_1:
    build:
      context: .
      dockerfile: node_dockerfile
    stdin_open: true
    tty: true
    networks: 
      - p2p_network
    volumes:
      - ./logs:/app/logs
    command: >
      bash -c "python secure_file_sender.py --mode leaf --ultrapeer ultrapeer_1"

  leaf_2:
    build:
      context: .
      dockerfile: node_dockerfile
    stdin_open: true
    tty: true
    networks: 
      - p2p_network
    volumes:
      - ./logs:/app/logs
    command: >
      bash -c "python secure_file_sender.py --mode leaf --ultrapeer ultrapeer_1"

networks:
  p2p_network:
    driver: bridge
