services:
  capture:
    build:
      context: .
      dockerfile: capture_dockerfile
    networks:
      - p2p_network
    volumes:
      - ./traffic_capture:/traffic_capture

  node_1:
    build:
      context: .
      dockerfile: node_dockerfile
    networks:
      - p2p_network
    volumes:
      - ./terminal_output:/terminal_output
    command: >
      bash -c "source venv/bin/activate && python secure_file_sender.py --mode ultrapeer > /terminal_output/node_1_output.txt 2>&1"

  node_2:
    build:
      context: .
      dockerfile: node_dockerfile
    networks: 
      - p2p_network
    volumes:
      - ./terminal_output:/terminal_output
    command: >
      bash -c "source venv/bin/activate && python secure_file_sender.py --mode leaf --ultrapeer node_1:8000 > /terminal_output/node_2_output.txt 2>&1"

networks:
  p2p_network:
    driver: bridge
