services:
  capture:
    build:
      context: .
      dockerfile: capture_dockerfile
    networks:
      - p2p_network
    volumes:
      - ./traffic_capture:/traffic_capture
  node_1:
    build:
      context: .
      dockerfile: node_dockerfile
    networks:
      - p2p_network
    command: ["bash", "-c", "source venv/bin/activate && python secure_file_sender.py", "--mode ultrapeer"]
  node_2:
    build:
      context: .
      dockerfile: node_dockerfile
    networks: 
      - p2p_network
    command: ["bash", "-c", "source venv/bin/activate && python secure_file_sender.py", "--mode leaf", "--ultrapeer node_1"]

networks:
  p2p_network:
    driver: bridge
